services:
  points-green-service:
    image: points_service:latest
    container_name: points-green-service
    ports:
      - "${POINTS_GREEN_PORT}:${POINTS_GREEN_PORT}"
    environment:
      SERVICE: ${POINTS_GREEN_SERVICE}
      PORT: ${POINTS_GREEN_PORT}
      MARIADB_PORT: ${POINTS_GREEN_MARIADB_PORT}
      MARIADB_HOST: host.docker.internal
      BEARER_TOKEN: ${BEARER_TOKEN}
    command: node src/index.js
    extra_hosts:
      - "host.docker.internal:host-gateway"

  points-red-service:
    image: points_service:latest
    container_name: points-red-service
    ports:
      - "${POINTS_RED_PORT}:${POINTS_RED_PORT}"
    environment:
      SERVICE: ${POINTS_RED_SERVICE}
      PORT: ${POINTS_RED_PORT}
      MARIADB_PORT: ${POINTS_RED_MARIADB_PORT}
      MARIADB_HOST: host.docker.internal
      BEARER_TOKEN: ${BEARER_TOKEN}
    command: node src/index.js
    extra_hosts:
      - "host.docker.internal:host-gateway"

  points-blue-service:
    image: points_service:latest
    container_name: points-blue-service
    ports:
      - "${POINTS_BLUE_PORT}:${POINTS_BLUE_PORT}"
    environment:
      SERVICE: ${POINTS_BLUE_SERVICE}
      PORT: ${POINTS_BLUE_PORT}
      MARIADB_PORT: ${POINTS_BLUE_MARIADB_PORT}
      MARIADB_HOST: host.docker.internal
      BEARER_TOKEN: ${BEARER_TOKEN}
    command: node src/index.js
    extra_hosts:
      - "host.docker.internal:host-gateway"

  points-central-service:
    image: points_service:latest
    container_name: points-central-service
    ports:
      - "${POINTS_CENTRAL_PORT}:${POINTS_CENTRAL_PORT}"
    environment:
      SERVICE: ${POINTS_CENTRAL_SERVICE}
      PORT: ${POINTS_CENTRAL_PORT}
      MARIADB_PORT: ${POINTS_CENTRAL_MARIADB_PORT}
      MARIADB_HOST: host.docker.internal
      BEARER_TOKEN: ${BEARER_TOKEN}
    command: node src/index.js
    extra_hosts:
      - "host.docker.internal:host-gateway"